### ISSUE TITLE
Why you'd be better off using QuickCheck when porting to Rust - Martin Hellspong

### ISSUE THREAD

**Issue by Hoverbear** [RustFestEU/transcript#7]

**Comment by marhel** [comment]
I'll do a quick check at the transcript of my own talk :)

**Comment by marhel** [comment]
A question, will you need the transcripts before I can have a look at the video? Because I guess it's better to match what was actually said in the video, rather than what I _think_ I said, now ten days later.

**Comment by skade** [comment]
Usually, transcripts are cleaned up with the video at hand (except the _big_ mistakes). There's no need of the transcript before the video is released. We won't add captions initially and they can be added later as metadata.
